import Head from 'next/head'
import styles from '../styles/home.module.css'
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Artsy Readme Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://d1s2w0upia4e9w.cloudfront.net/images/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.home}>
            <div className={styles.center}>
                <div className={styles.company}>Artsy README</div>
                <Link href="/docs" passHref>
                    <button className={styles.button}>View our docs</button>
                </Link>
            </div>
        </div>
      </main>
    </div>
  )
}
